### ISSUE TITLE
Had pity day not working

### ISSUE THREAD

**Issue by PseudoCoffee** [hatfielddr/Random-Sell-Prices#1]
It happened multiple times for me but the pity day feature seems to not work, and after checking the code, it seems that hadPityDay is static and set false only once while this should be set to false after each end of quota.

**Comment by hatfielddr** [comment]
Ah yeah you're so right! Can't believe I overlooked that lol I'll get a fix out asap

**Comment by hatfielddr** [comment]
Fixed in v1.0.1 release, mod should update on thunderstore soon
